### ISSUE TITLE
WHere to find API details?

### ISSUE THREAD

**Issue by cTatu** [keallu/CSL-ZoneIt#3]
Hi,

Where did you find the `RoadAI` class in order to reference it in the HarmonyPatch?
https://github.com/keallu/CSL-ZoneIt/blob/c94fcba69325e6949aa72fac2c66589e2bf94bf7/ZoneIt/Patches.cs#L5-L10

I was looking around the [Cities Skylines Modding Documentation](https://skylines.paradoxwikis.com/Modding_API) but it doesn't mention anywhere `RoadAI` class. I suppose you reverse engineered the `Assembly-Csharp.dll`. Is there documentation for all the classes, methods and functionality in these `.dll`? I was hoping to try make a mod that would add a new type of District, but in these conditions, it'll be more time-consuming figuring out all the API than writing the code 😓.

Thank you

**Comment by keallu** [comment]
Yes to reverse engineering, no to documentation.
